name:  benchmark_env
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - pip:
    - gpjax==0.6.7
    - jax==0.4.9
    - jaxkern
    - jaxlib==0.4.7
    - jaxlinop
    - jaxtyping
    - jaxutils
    - jinja2
    - flask
    - markupsafe
    - ml-collections
    - matplotlib
    - numpy
    - imageio
    - optax
    - pre-commit
    - py
    - pyfoam
    - pytest
    - pyyaml
    - scipy
    - toml
    - toolz
    - tqdm
    - typeguard
    - virtualenv
